package com.centrahub.SCinsert;

public class SaasHVar {
	
/*	 iMasterId,
	 AdditionalExternalUser, 
	 AdditionalLightUser,
	 AmountLocal, 
	 BaseUser,
	 LicenseType,
	 LightUser,
	 NetAmountLocal,
	 NetAmountUSD,
	 Quantity, 
	 ResellerPercentage,
	 SalePercentage, 
	 StreamType, 
	 Tax1, 
	 Tax1Amount,
	 Tax2,
	 Tax2Amount,
	 Tax3,
	 Tax3Amount,
	 TaxAmountLocal, 
	 TaxAmountUSD,
	 TaxCode,
	 TaxPercentage , 
	 iProductId,
	 ProductDescription, 
	 SaleLicensePrice,
	 StdLicensePriceLocal,
	 iProductGroupId,
	 NoofUsers,
	 fPerUserAmount,
	 fAdditionalUserCost,
	 fLightUsersCost, 
	 iLightUserPercent,
	 iCreatedDate,
	 AdditionalUser*/

}
